//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVoice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category : IVoice.Helpers.IEntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.ForumTopics = new HashSet<ForumTopic>();
            this.UsersIPs = new HashSet<UsersIP>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FeatureId { get; set; }
        public string Name { get; set; }
        public bool OnlyForum { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> UserIdCreate { get; set; }
        public int Topics { get; set; }
        public int Posts { get; set; }
        public Nullable<int> LastUserId { get; set; }
        public Nullable<int> LastTopicId { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public bool Enabled { get; set; }
        public bool ForIP { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual ForumTopic ForumTopic { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumTopic> ForumTopics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersIP> UsersIPs { get; set; }
    }
}
