//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVoice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumTopicsView
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public int TopicId { get; set; }
        public string Ip { get; set; }
    
        public virtual ForumTopic ForumTopic { get; set; }
        public virtual User User { get; set; }
    }
}
