//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVoice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumTopic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForumTopic()
        {
            this.Categories = new HashSet<Category>();
            this.ForumAnswers = new HashSet<ForumAnswer>();
            this.ForumTopicsViews = new HashSet<ForumTopicsView>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> AnswerId { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Views { get; set; }
        public int Replies { get; set; }
        public bool Active { get; set; }
        public System.DateTime LastReplyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumAnswer> ForumAnswers { get; set; }
        public virtual ForumAnswer ForumAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumTopicsView> ForumTopicsViews { get; set; }
        public virtual User User { get; set; }
    }
}
