//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVoice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersIPFilter : IVoice.Helpers.IEntityBase
    {
        public int Id { get; set; }
        public int UsersIPId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string BirthDate { get; set; }
        public string RelationshipStatus { get; set; }
        public string Region { get; set; }
        public string Language { get; set; }
        public string OccupationByComma { get; set; }
        public string HobbiesByComma { get; set; }
    
        public virtual UsersIP UsersIP { get; set; }
    }
}
