//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVoice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersIPTag : IVoice.Helpers.IEntityBase
    {
        public int Id { get; set; }
        public int UserIPId { get; set; }
        public int IPTagId { get; set; }
    
        public virtual IPTag IPTag { get; set; }
        public virtual UsersIP UsersIP { get; set; }
    }
}
