//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVoice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersIPComment : IVoice.Helpers.IEntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersIPComment()
        {
            this.UsersIPComments1 = new HashSet<UsersIPComment>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int UsersIPId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public int Pos { get; set; }
    
        public virtual User User { get; set; }
        public virtual UsersIP UsersIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersIPComment> UsersIPComments1 { get; set; }
        public virtual UsersIPComment UsersIPComment1 { get; set; }
    }
}
