//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVoice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPayment : IVoice.Helpers.IEntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersPayment()
        {
            this.UsersCPMBalances = new HashSet<UsersCPMBalance>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal TotalCPM { get; set; }
        public decimal TotalPayed { get; set; }
        public string PaymentCode { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersCPMBalance> UsersCPMBalances { get; set; }
    }
}
