//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVoice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersIPAd : IVoice.Helpers.IEntityBase
    {
        public int Id { get; set; }
        public int TotalClicks { get; set; }
        public int MaxClicks { get; set; }
        public decimal ClickValue { get; set; }
        public bool Active { get; set; }
        public System.DateTime Data { get; set; }
        public int Views { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> OcupationId { get; set; }
        public Nullable<int> InterestId { get; set; }
        public string DateBirth { get; set; }
        public string Region { get; set; }
        public string Language { get; set; }
        public string RelationShipStatus { get; set; }
        public int Position { get; set; }
    
        public virtual UsersIP UsersIP { get; set; }
    }
}
