//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVoice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whisper : IVoice.Helpers.IEntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Whisper()
        {
            this.WhisperAttachments = new HashSet<WhisperAttachment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public int UserSenderId { get; set; }
        public int UserReceiverId { get; set; }
        public bool DeleteSender { get; set; }
        public bool DeleteReceiver { get; set; }
        public bool ReadSender { get; set; }
        public bool ReadReceiver { get; set; }
        public System.DateTime DateSent { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WhisperAttachment> WhisperAttachments { get; set; }
    }
}
